#!/bin/bash

print_usage(){
    echo "ganymede [-s] [-e] [-h] [-p PORT] [-v VOLUME] [-n NAME]"
}

start(){
    local LOGFILE=$(mktemp)
    echo LOGFILE=${LOGFILE}
    docker run --rm -v ${VOLUME}:/root/work -p ${PORT}:8888 --name ${NAME} hotokudtws/ganymede > ${LOGFILE} 2>&1 &
    local PID=$!
    sleep 3
    if ! ps -p ${PID} > /dev/null; then
        cat ${LOGFILE}
        exit 1
    fi
    local TOKEN=$(grep "http://127.0.0.1:8888" ${LOGFILE} | tail -n1 | sed -E "s/.+token=(.+)/\1/")
    URL=http://localhost:${PORT}/?token=${TOKEN}
    echo URL=${URL}
    open ${URL}
}

end(){
    docker stop ${NAME}
}

set_cmd(){
    if ! [ -z "${CMD}" ]; then
        echo "Error: 2 of -s and -e are given"
        exit 1
    fi
    CMD=$1
}

CMD=""
PORT=8888
VOLUME=$(pwd)
NAME=ganymede
while getopts sep:v:n:h OPT; do
    case ${OPT} in
        s) set_cmd start ;;
        e) set_cmd end ;;
        p) PORT=${OPTARG} ;;
        v) VOLUME=${OPTARG} ;;
        n) NAME=${OPTARG} ;;
        h) print_usage; exit ;;
    esac
done

if [ -z ${CMD} ]; then
    CMD=start
fi
${CMD}

# Local Variables:
# mode: Shell-script
# End:
