#!/bin/bash

print_usage(){
    echo "ganymede [-s] [-e] [-h] [-p PORT] [-v VOLUME] [-n NAME]"
}

start(){
    local LOGFILE=$(mktemp)
    echo LOGFILE=${LOGFILE}
    docker run --rm -v ${VOLUME}:/root/work -p ${PORT}:8888 --name ${NAME} hotokudtws/ganymede > ${LOGFILE} 2>&1 &
    local PID=$!
    sleep 3
    if ! ps -p ${PID} > /dev/null; then
        cat ${LOGFILE}
        exit 1
    fi
    local URL=$(grep "http://127.0.0.1:8888" ${LOGFILE} | tail -n1 | sed -E "s/.+(http:)/\1/")
    echo ${URL}
    open ${URL}
}

end(){
    docker stop ${NAME}
}

CMD=start
PORT=8888
VOLUME=$(pwd)
NAME=ganymede
getopts sep:v:n:h OPT
case ${OPT} in
    s) CMD=start ;;
    e) CMD=end ;;
    p) PORT=${OPTARG} ;;
    v) VOLUME=${OPTARG} ;;
    n) NAME=${OPTARG} ;;
    h) print_usage; exit ;;
esac

${CMD}

# Local Variables:
# mode: Shell-script
# End:
